"""Builtin tool to execute script commands declared inside installed skills."""

from __future__ import annotations

import asyncio
import difflib
import os
import shutil
import re
import shlex
import sys
from pathlib import Path
from typing import Any

from src.bootstrap import default_skills_path
from src.skills.base import BaseTool, ToolResult
from src.skills.execution_guard import ExecutionAdvisor, ExecutionGuard
from src.utils.logging import get_logger

logger = get_logger(__name__)


class SkillScriptRunnerTool(BaseTool):
    """Run bash commands for scripts under ~/.semibot/skills/<skill>/scripts safely."""

    def __init__(self) -> None:
        self.skills_root = Path(
            os.getenv("SEMIBOT_SKILLS_PATH", str(default_skills_path()))
        ).expanduser().resolve()
        self.default_timeout = int(os.getenv("SEMIBOT_SKILL_SCRIPT_TIMEOUT") or "180")
        self.max_output_chars = int(os.getenv("SEMIBOT_SKILL_SCRIPT_MAX_OUTPUT_CHARS") or "20000")
        self.guard = ExecutionGuard()
        self.advisor = ExecutionAdvisor()
        self._artifact_claim_pattern = re.compile(
            r"(?i)(saved to|written to|output(?: file)?|generated(?: file)?|created(?: file)?)\s*:\s*(/[^\\\s'\"`]+\.[a-z0-9]+)"
        )
        self._artifact_future_markers = (
            "will ",
            "would ",
            "should ",
            "to be ",
            "expected ",
            "planned ",
        )

    @property
    def name(self) -> str:
        return "skill_script_runner"

    @property
    def description(self) -> str:
        return (
            "Execute a bash command for an installed skill. "
            "Command must target files under skill/scripts/. "
            "Use after reading SKILL.md and following its command guidance. "
            "If command arguments reference files generated by previous steps, use the exact artifact path "
            "provided by runtime context; do not use bare filenames or guessed relative paths."
        )

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "skill_name": {
                    "type": "string",
                    "description": "Installed skill id, e.g. deep-research",
                },
                "command": {
                    "type": "string",
                    "description": (
                        "Bash command targeting a real file under the selected skill's scripts/ directory. "
                        "If any CLI argument references a file generated by previous steps, you must use the exact "
                        "artifact path provided in runtime context (prefer absolute_path). "
                        "Never use bare filenames like report.md or guessed relative paths. "
                        "Runtime validates paths but will not rewrite them. "
                        "Example: python scripts/validate_report.py --report /abs/path/report.md"
                    ),
                },
                "timeout": {
                    "type": "integer",
                    "description": "Timeout in seconds",
                    "default": 180,
                },
            },
            "required": ["skill_name", "command"],
        }

    def _resolve_skill_root(self, skill_name: str) -> Path:
        skill = skill_name.strip()
        if not skill:
            raise ValueError("skill_name is required")
        validation = self.guard.validate_skill_exists(self.skills_root, skill)
        if validation.blocked:
            raise ValueError(validation.reason or f"skill not found: {skill}")
        skill_root = (self.skills_root / skill).resolve()
        return skill_root

    @staticmethod
    def _looks_like_script_filename(token: str) -> bool:
        candidate = token.strip().strip("'\"")
        if "/" in candidate or "\\" in candidate:
            return False
        return bool(re.search(r"\.(py|js|mjs|cjs|sh|bash|ts)$", candidate, flags=re.IGNORECASE))

    @staticmethod
    def _basename(path: str) -> str:
        return path.replace("\\", "/").split("/")[-1]

    def _guess_existing_script(self, missing_rel: str, available_scripts: list[str]) -> str | None:
        if not available_scripts:
            return None
        normalized_missing = missing_rel.replace("\\", "/")
        missing_name = self._basename(normalized_missing)
        available_names = {self._basename(item): item for item in available_scripts}
        if missing_name in available_names:
            return available_names[missing_name]
        close = difflib.get_close_matches(missing_name, list(available_names.keys()), n=1, cutoff=0.72)
        if close:
            return available_names.get(close[0])
        return None

    def _validate_command(self, command: str, skill_root: Path) -> tuple[list[str], list[str]]:
        if not command.strip():
            raise ValueError("command is required")
        # Ensure command references at least one scripts/* path inside the skill.
        parts = shlex.split(command, posix=True)
        if not parts:
            raise ValueError("invalid command")

        found_script_ref = False
        rewrites: list[str] = []
        available_scripts: list[str] = sorted(
            str(p.relative_to(skill_root)).replace("\\", "/")
            for p in (skill_root / "scripts").glob("*")
            if p.is_file()
        ) if (skill_root / "scripts").exists() else []
        normalized_parts: list[str] = []
        for token in parts:
            normalized = token.strip().strip("'\"").replace("\\", "/")
            if "scripts/" not in normalized:
                if self._looks_like_script_filename(normalized):
                    guessed = f"scripts/{normalized}"
                    guessed_path = (skill_root / guessed).resolve()
                    if guessed_path.exists():
                        found_script_ref = True
                        rewrites.append(f"{normalized} -> {guessed}")
                        normalized_parts.append(guessed)
                        continue
                normalized_parts.append(token)
                continue
            idx = normalized.find("scripts/")
            rel = normalized[idx:]
            if rel.startswith("/") or rel.startswith("~"):
                normalized_parts.append(token)
                continue
            if any(seg == ".." for seg in rel.split("/")):
                raise ValueError("script path escapes skill root")
            candidate = (skill_root / rel).resolve()
            if candidate != skill_root and skill_root not in candidate.parents:
                raise ValueError("script path escapes skill root")
            validation = self.guard.validate_script_path(skill_root, rel)
            if validation.blocked and validation.reason != "script_not_found":
                raise ValueError(validation.reason)
            if not candidate.exists():
                guessed_rel = self._guess_existing_script(rel, available_scripts)
                if guessed_rel:
                    rewrites.append(f"{rel} -> {guessed_rel}")
                    normalized_parts.append(token.replace(rel, guessed_rel))
                    found_script_ref = True
                    continue
                hint = ", ".join(available_scripts[:12]) if available_scripts else "none"
                raise ValueError(f"script target not found: {rel}. available scripts: {hint}")
            found_script_ref = True
            normalized_parts.append(token)
        if not found_script_ref:
            hint = ", ".join(available_scripts[:12]) if available_scripts else "none"
            raise ValueError(
                "command must reference at least one file under scripts/. "
                f"available scripts: {hint}"
            )
        normalized_parts = self._normalize_command_interpreter(normalized_parts)
        self._enforce_safe_entrypoint(normalized_parts)
        return normalized_parts, rewrites

    @staticmethod
    def _is_env_assignment(token: str) -> bool:
        text = str(token or "").strip()
        if not text or "=" not in text or text.startswith("-"):
            return False
        key, _, _value = text.partition("=")
        return bool(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key))

    @staticmethod
    def _is_allowed_interpreter(token: str) -> bool:
        candidate = Path(str(token or "").strip().strip("'\"")).name.lower()
        return candidate in {
            "python",
            "python3",
            "python3.10",
            "python3.11",
            "python3.12",
            "node",
            "bash",
            "sh",
            "zsh",
        }

    @staticmethod
    def _normalize_path_token(token: str) -> str:
        return str(token or "").strip().strip("'\"").replace("\\", "/")

    def _find_leading_script_argument_index(self, parts: list[str], start_idx: int) -> int | None:
        idx = start_idx
        while idx < len(parts):
            token = self._normalize_path_token(parts[idx])
            if not token:
                idx += 1
                continue
            if token.startswith("-"):
                idx += 1
                continue
            if token.startswith("scripts/"):
                return idx
            return None
        return None

    def _enforce_safe_entrypoint(self, parts: list[str]) -> None:
        if not parts:
            raise ValueError("invalid command")
        cmd_idx = 0
        while cmd_idx < len(parts) and self._is_env_assignment(parts[cmd_idx]):
            cmd_idx += 1
        if cmd_idx >= len(parts):
            raise ValueError("invalid command")

        entry = self._normalize_path_token(parts[cmd_idx])
        if entry.startswith("scripts/"):
            return

        if self._is_allowed_interpreter(entry):
            script_idx = self._find_leading_script_argument_index(parts, cmd_idx + 1)
            if script_idx is not None:
                return
            raise ValueError(
                "command must execute a script under scripts/ as the primary entrypoint, "
                "for example: python scripts/<name>.py ..."
            )

        raise ValueError(
            "command entrypoint is not allowed. Use a script under scripts/ directly "
            "or an allowed interpreter (python/python3/node/bash/sh/zsh) with scripts/<name>."
        )

    @staticmethod
    def _normalize_command_interpreter(parts: list[str]) -> list[str]:
        if not parts:
            return []
        normalized = list(parts)
        has_python = shutil.which("python") is not None
        if not has_python:
            fallback = shutil.which("python3") or shutil.which("python3.11") or shutil.which("python3.10")
            if fallback:
                fallback_name = Path(fallback).name
                normalized = [fallback_name if token == "python" else token for token in normalized]
        return normalized

    def _trim(self, text: bytes) -> tuple[str, bool]:
        decoded = text.decode("utf-8", errors="replace")
        if len(decoded) <= self.max_output_chars:
            return decoded, False
        return decoded[: self.max_output_chars], True

    def _extract_claimed_artifacts(self, *texts: str) -> list[str]:
        claimed: list[str] = []
        for text in texts:
            for line in str(text or "").splitlines():
                lowered = line.strip().lower()
                if not lowered:
                    continue
                if any(marker in lowered for marker in self._artifact_future_markers):
                    continue
                for _label, path in self._artifact_claim_pattern.findall(line):
                    normalized = str(path or "").strip()
                    if normalized and normalized not in claimed:
                        claimed.append(normalized)
        return claimed

    # ── Auto-install helpers ──────────────────────────────────────────

    _RE_PYTHON_MISSING = re.compile(r"No module named ['\"]([^'\"]+)['\"]")
    _RE_JS_MISSING = re.compile(r"Cannot find (?:module|package) ['\"]([^'\"]+)['\"]")

    _PYTHON_MODULE_TO_PACKAGE: dict[str, str] = {
        "pptx": "python-pptx",
        "docx": "python-docx",
        "PIL": "Pillow",
        "markitdown": "markitdown[pptx]",
    }

    @staticmethod
    def _detect_missing_python_module(stderr: str) -> str | None:
        match = SkillScriptRunnerTool._RE_PYTHON_MISSING.search(stderr)
        if match:
            return match.group(1).split(".")[0]
        return None

    @staticmethod
    def _detect_missing_js_module(stderr: str) -> str | None:
        match = SkillScriptRunnerTool._RE_JS_MISSING.search(stderr)
        if match:
            return match.group(1).split("/")[0]
        return None

    @staticmethod
    async def _auto_install_python(module_name: str) -> bool:
        if str(os.getenv("SEMIBOT_ENABLE_CODE_AUTO_INSTALL", "")).strip().lower() not in {"1", "true", "yes", "on"}:
            logger.info("auto_installed_python_dep: auto-install disabled for module %s", module_name)
            return False
        if module_name not in SkillScriptRunnerTool._PYTHON_MODULE_TO_PACKAGE:
            logger.warning("auto_installed_python_dep: module %s is not in the allowlist", module_name)
            return False
        package = SkillScriptRunnerTool._PYTHON_MODULE_TO_PACKAGE.get(module_name, module_name)
        logger.info("auto_installed_python_dep: attempting pip install %s (module: %s)", package, module_name)
        try:
            proc = await asyncio.create_subprocess_exec(
                sys.executable, "-m", "pip", "install", "--quiet", package,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, err = await asyncio.wait_for(proc.communicate(), timeout=120)
            if proc.returncode == 0:
                logger.info("auto_installed_python_dep: successfully installed %s", package)
                return True
            logger.warning("auto_installed_python_dep: pip install %s failed: %s", package, err.decode(errors="replace"))
        except Exception as exc:
            logger.warning("auto_installed_python_dep: error installing %s: %s", package, exc)
        return False

    @staticmethod
    async def _auto_install_js_global(module_name: str) -> bool:
        logger.warning("auto_installed_js_dep: auto-install is disabled for module %s", module_name)
        return False

    # ── End auto-install helpers ──────────────────────────────────────

    async def execute(
        self,
        skill_name: str,
        command: str,
        timeout: int | None = None,
        **_: Any,
    ) -> ToolResult:
        try:
            skill_root = self._resolve_skill_root(skill_name)
            command_parts, rewrites = self._validate_command(command, skill_root)
        except Exception as exc:
            return ToolResult.error_result(str(exc))
        safe_command = shlex.join(command_parts)
        script_path, script_args = self.advisor.split_command_args(safe_command)
        if script_path:
            advisory = self.advisor.check_script_help(skill_root, script_path, script_args)
            if advisory.level == "error":
                return ToolResult.error_result(
                    advisory.message,
                    advisory={
                        "level": advisory.level,
                        "message": advisory.message,
                    },
                    script_help=advisory.help_text_snippet,
                    command=command,
                    resolved_command=safe_command,
                )
        else:
            advisory = None

        final_timeout = timeout if isinstance(timeout, int) and timeout > 0 else self.default_timeout

        try:
            proc = await asyncio.create_subprocess_exec(
                *command_parts,
                cwd=str(skill_root),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            try:
                stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=final_timeout)
            except asyncio.TimeoutError:
                proc.kill()
                await proc.wait()
                return ToolResult.error_result(f"command timed out after {final_timeout}s")

            trimmed_stdout, stdout_truncated = self._trim(stdout or b"")
            trimmed_stderr, stderr_truncated = self._trim(stderr or b"")
            payload = {
                "skill_name": skill_name,
                "command": command,
                "resolved_command": safe_command,
                "command_rewrites": rewrites,
                "exit_code": int(proc.returncode or 0),
                "stdout": trimmed_stdout,
                "stderr": trimmed_stderr,
                "stdout_truncated": stdout_truncated,
                "stderr_truncated": stderr_truncated,
            }
            if advisory and advisory.level in {"warning", "info"}:
                payload["advisory"] = advisory.message
                if advisory.help_text_snippet:
                    payload["script_help"] = advisory.help_text_snippet
            claimed_artifacts = self._extract_claimed_artifacts(trimmed_stdout, trimmed_stderr)
            if claimed_artifacts:
                payload["claimed_artifacts"] = claimed_artifacts
                missing_artifacts = [
                    artifact
                    for artifact in claimed_artifacts
                    if not Path(artifact).expanduser().exists()
                ]
                if missing_artifacts:
                    payload["missing_claimed_artifacts"] = missing_artifacts
                    advisory_payload = {
                        "level": "error",
                        "message": (
                            "script claimed artifact(s) that do not exist: "
                            + ", ".join(missing_artifacts)
                        ),
                    }
                    return ToolResult.error_result(
                        advisory_payload["message"],
                        advisory=advisory_payload,
                        payload=payload,
                    )
            if proc.returncode != 0:
                # Auto-install missing dependencies and retry once
                missing_py = self._detect_missing_python_module(trimmed_stderr)
                missing_js = self._detect_missing_js_module(trimmed_stderr)
                retried = False

                if missing_py:
                    installed = await self._auto_install_python(missing_py)
                    if installed:
                        retried = True
                elif missing_js:
                    installed = await self._auto_install_js_global(missing_js)
                    if installed:
                        retried = True

                if retried:
                    proc2 = await asyncio.create_subprocess_exec(
                        *command_parts,
                        cwd=str(skill_root),
                        stdout=asyncio.subprocess.PIPE,
                        stderr=asyncio.subprocess.PIPE,
                    )
                    try:
                        stdout2, stderr2 = await asyncio.wait_for(proc2.communicate(), timeout=final_timeout)
                    except asyncio.TimeoutError:
                        proc2.kill()
                        await proc2.wait()
                        return ToolResult.error_result(f"command timed out after {final_timeout}s (retry)")

                    trimmed_stdout, stdout_truncated = self._trim(stdout2 or b"")
                    trimmed_stderr, stderr_truncated = self._trim(stderr2 or b"")
                    payload.update({
                        "exit_code": int(proc2.returncode or 0),
                        "stdout": trimmed_stdout,
                        "stderr": trimmed_stderr,
                        "stdout_truncated": stdout_truncated,
                        "stderr_truncated": stderr_truncated,
                    })
                    # Re-check claimed artifacts after retry
                    claimed_artifacts = self._extract_claimed_artifacts(trimmed_stdout, trimmed_stderr)
                    if claimed_artifacts:
                        payload["claimed_artifacts"] = claimed_artifacts
                    if proc2.returncode == 0:
                        return ToolResult.success_result(payload)

                stdout_summary = trimmed_stdout.strip()
                stderr_summary = trimmed_stderr.strip()
                message = stderr_summary or stdout_summary or f"command failed with exit code {payload['exit_code']}"
                return ToolResult.error_result(message, **payload)
            return ToolResult.success_result(payload)
        except Exception as exc:
            return ToolResult.error_result(f"command execution failed: {exc}")
